# Generated by Django 4.1.7 on 2023-03-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_password_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
